[wokwi]
version = 1
elf = 'test/graphicstest/build/arduino.avr.uno/graphicstest.ino.elf'
firmware = 'test/graphicstest/build/arduino.avr.uno/graphicstest.ino.hex'

[[chip]]
name = 'GC9A01'
binary = 'dist/chip.wasm'
